srv=net.createServer(net.TCP)
srv:listen(80,function(conn)
	conn:on("receive",function(conn,payload)
		print(payload)
		conn:send("<pre>"..payload.."</pre>")
		conn:close()
	end)
	conn:on("sent",function(conn)

	end)
end)
